spring.application.name=hello-service
server.port=8080

logging.file.name=logs/hello-service.log
logging.pattern.file={"time":"%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}","level":"%level","logger":"%logger{36}","message":"%msg"}%n
